version: '3.7'

services:
  postgres:
    image: 'postgres:12'
    networks:
      - djangonetwork
    volumes:
      - ./docker/postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    networks:
      - djangonetwork
    build:
      context: .
    entrypoint:
      - /entrypoint.sh
    depends_on:
      - postgres
    links:
      - postgres
    expose:
      - 8000
networks:
  djangonetwork:
